/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.JPanel;

/**
 *
 * @author abdel
 */
public class messageCard extends javax.swing.JPanel {

    /**
     * Creates new form messageCard
     */
    public messageCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 2, 36)); // NOI18N
        jLabel3.setText("sorry you should pay 200");
        add(jLabel3);
        jLabel3.setBounds(140, 130, 450, 240);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/gooo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(310, 400, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/oooooo.jpg"))); // NOI18N
        jLabel1.setText("ddd");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
