/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.border.EmptyBorder;

/**
 *
 * @author Taher
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public StartPage() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Start_btn = new javax.swing.JButton();
        Exit_btn = new javax.swing.JButton();
        Score_btn = new javax.swing.JButton();
        gif_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 100));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        Start_btn.setBackground(new java.awt.Color(0, 51, 51));
        Start_btn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Start_btn.setForeground(new java.awt.Color(204, 255, 255));
        Start_btn.setText("Start");
        Start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Start_btn);
        Start_btn.setBounds(30, 130, 150, 47);

        Exit_btn.setBackground(new java.awt.Color(0, 51, 51));
        Exit_btn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Exit_btn.setForeground(new java.awt.Color(204, 255, 255));
        Exit_btn.setText("Exit");
        Exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Exit_btn);
        Exit_btn.setBounds(30, 290, 150, 47);

        Score_btn.setBackground(new java.awt.Color(0, 51, 51));
        Score_btn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Score_btn.setForeground(new java.awt.Color(204, 255, 255));
        Score_btn.setText("Help");
        Score_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Score_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Score_btn);
        Score_btn.setBounds(30, 210, 150, 47);

        gif_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/gif1.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gif_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addGap(3, 3, 3))
            .addComponent(gif_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_btnActionPerformed
        dispose();
        new StartPage2().setVisible(rootPaneCheckingEnabled);        // TODO add your handling code here:
    }//GEN-LAST:event_Start_btnActionPerformed

    private void Exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btnActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Exit_btnActionPerformed

    private void Score_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Score_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Score_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_btn;
    private javax.swing.JButton Score_btn;
    private javax.swing.JButton Start_btn;
    private javax.swing.JLabel gif_lbl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
